name: Prettier Action

on:
  push

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false

      - name: Commit URL
        run: git remote set-url https://github-actions:${{github.token}}@github.com/rbjks/rbjks.github.io.git

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: False
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
